webserv: server.o
	gcc -o webserv server.o

server.o: server.c
	gcc -c server.c -o server.o
	
webserv2: server2.o
	gcc -o webserv2 server2.o

server2.o: server2.c
	gcc -c server2.c -o server2.o
	

webclient: client.o
	gcc client.o -o webclient

client.o: client.c
	gcc -c client.c -o client.o
	
webserv3: server3.o
	gcc -o webserv3 server3.o

server3.o: server3.c
	gcc -c server3.c -o server3.o
	
